---
classes:
  - class_id: "676a616b9c1900057ea130b2"
    lab_resources:
      - display_name: "Linux"
        platform_type: "lab"
        image_platform: "linux"
        view_interface: "terminal"
        cloud_provider: "aws"
        aws_vm_definition:
          machine_size: "t3.micro"
          ami_region_mapping:
            eu-west-1:
              image_id: "ami-0754c1bf35f85d01f"
          custom_username: "ubuntu"
        user_data: |
          #!/bin/bash

          echo "hello world" > /tmp/myfile.txt
    exercises:
      - file: "../exercises/exercise01.md"
        title: "Exercise 01"
        syntax: "md"
  - class_id: "676a66449c1900057ea131df"
    lab_resources:
      - display_name: "Windows test"
        platform_type: "lab"
        image_platform: "windows"
        view_interface: "desktop"
        cloud_provider: "aws"
        aws_vm_definition:
          machine_size: "t3.large"
          ami_region_mapping:
            eu-west-1:
              image_id: "ami-0afcd9cce919e7a9c"
          custom_username: "Administrator"
        post_launch_script: |
          <powershell>
            echo "do something"
          </powershell>

