---
classes:
  - lab_resources:
      - display_name: "Lab"
        platform_type: "lab"
        image_platform: "linux"
        view_interface: "terminal"
        cloud_provider: "foo"
        aws_vm_definition:
          machine_size: "t2.micro"
          ami_region_mapping:
            eu-west-1:
              image_id: "ami-0754c1bf35f85d01f"
          custom_username: "ubuntu"
