---
classes:
  - lab_resources:
      - display_name: "Linux 6"
        platform_type: "lab"
        image_platform: "linux"
        view_interface: "desktop"
        cloud_provider: "aws"
        aws_vm_definition:
          machine_size: "t3.micro"
          ami_region_mapping:
            eu-west-1:
              image_id: "ami-0754c1bf35f85d01f"
          custom_username: "ubuntu"
        user_data: |
          #!/bin/bash

          echo "hello world" > /tmp/myfile.txt
    exercises:
      - file: "../exercises/exercise01.md"
        title: "Exercise 01"
        syntax: "md"
